// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// NewExportParams creates a new ExportParams object
//
// There are no default values defined in the spec.
func NewExportParams() ExportParams {

	return ExportParams{}
}

// ExportParams contains all the bound params for the export operation
// typically these are obtained from a http.Request
//
// swagger:parameters export
type ExportParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The shortened URLs to get the export for. If null, an export of all shortened URLs will be given.
	  In: body
	*/
	ShortenedURLs []string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewExportParams() beforehand.
func (o *ExportParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body []string
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("shortenedURLs", "body", "", err))
		} else {
			// no validation required on inline body
			o.ShortenedURLs = body
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
