// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MicahParks/terseurl/models"
)

// FrontendMetaOKCode is the HTTP code returned for type FrontendMetaOK
const FrontendMetaOKCode int = 200

/*FrontendMetaOK The relevant HTML meta tag information.

swagger:response frontendMetaOK
*/
type FrontendMetaOK struct {

	/*
	  In: Body
	*/
	Payload *FrontendMetaOKBody `json:"body,omitempty"`
}

// NewFrontendMetaOK creates FrontendMetaOK with default headers values
func NewFrontendMetaOK() *FrontendMetaOK {

	return &FrontendMetaOK{}
}

// WithPayload adds the payload to the frontend meta o k response
func (o *FrontendMetaOK) WithPayload(payload *FrontendMetaOKBody) *FrontendMetaOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the frontend meta o k response
func (o *FrontendMetaOK) SetPayload(payload *FrontendMetaOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FrontendMetaOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*FrontendMetaDefault Unexpected error.

swagger:response frontendMetaDefault
*/
type FrontendMetaDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFrontendMetaDefault creates FrontendMetaDefault with default headers values
func NewFrontendMetaDefault(code int) *FrontendMetaDefault {
	if code <= 0 {
		code = 500
	}

	return &FrontendMetaDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the frontend meta default response
func (o *FrontendMetaDefault) WithStatusCode(code int) *FrontendMetaDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the frontend meta default response
func (o *FrontendMetaDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the frontend meta default response
func (o *FrontendMetaDefault) WithPayload(payload *models.Error) *FrontendMetaDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the frontend meta default response
func (o *FrontendMetaDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FrontendMetaDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
