// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// NewFrontendMetaParams creates a new FrontendMetaParams object
//
// There are no default values defined in the spec.
func NewFrontendMetaParams() FrontendMetaParams {

	return FrontendMetaParams{}
}

// FrontendMetaParams contains all the bound params for the frontend meta operation
// typically these are obtained from a http.Request
//
// swagger:parameters frontendMeta
type FrontendMetaParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The original URL to HTTP GET and extract the relevant HTML meta from for social media link previews.
	  Required: true
	  In: body
	*/
	OriginalURL string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewFrontendMetaParams() beforehand.
func (o *FrontendMetaParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body string
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("originalUrl", "body", ""))
			} else {
				res = append(res, errors.NewParseError("originalUrl", "body", "", err))
			}
		} else {
			// no validation required on inline body
			o.OriginalURL = body
		}
	} else {
		res = append(res, errors.Required("originalUrl", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
