// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MicahParks/terseurl/models"
)

// ImportOKCode is the HTTP code returned for type ImportOK
const ImportOKCode int = 200

/*ImportOK The import request was successfully fulfilled.

swagger:response importOK
*/
type ImportOK struct {
}

// NewImportOK creates ImportOK with default headers values
func NewImportOK() *ImportOK {

	return &ImportOK{}
}

// WriteResponse to the client
func (o *ImportOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*ImportDefault Unexpected error.

swagger:response importDefault
*/
type ImportDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewImportDefault creates ImportDefault with default headers values
func NewImportDefault(code int) *ImportDefault {
	if code <= 0 {
		code = 500
	}

	return &ImportDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the import default response
func (o *ImportDefault) WithStatusCode(code int) *ImportDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the import default response
func (o *ImportDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the import default response
func (o *ImportDefault) WithPayload(payload *models.Error) *ImportDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the import default response
func (o *ImportDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ImportDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
