// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MicahParks/terseurl/models"
)

// ShortenedURLPrefixOKCode is the HTTP code returned for type ShortenedURLPrefixOK
const ShortenedURLPrefixOKCode int = 200

/*ShortenedURLPrefixOK The HTTP prefix all shortened URLs have.

swagger:response shortenedUrlPrefixOK
*/
type ShortenedURLPrefixOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewShortenedURLPrefixOK creates ShortenedURLPrefixOK with default headers values
func NewShortenedURLPrefixOK() *ShortenedURLPrefixOK {

	return &ShortenedURLPrefixOK{}
}

// WithPayload adds the payload to the shortened Url prefix o k response
func (o *ShortenedURLPrefixOK) WithPayload(payload string) *ShortenedURLPrefixOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the shortened Url prefix o k response
func (o *ShortenedURLPrefixOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ShortenedURLPrefixOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*ShortenedURLPrefixDefault Unexpected error.

swagger:response shortenedUrlPrefixDefault
*/
type ShortenedURLPrefixDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewShortenedURLPrefixDefault creates ShortenedURLPrefixDefault with default headers values
func NewShortenedURLPrefixDefault(code int) *ShortenedURLPrefixDefault {
	if code <= 0 {
		code = 500
	}

	return &ShortenedURLPrefixDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the shortened URL prefix default response
func (o *ShortenedURLPrefixDefault) WithStatusCode(code int) *ShortenedURLPrefixDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the shortened URL prefix default response
func (o *ShortenedURLPrefixDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the shortened URL prefix default response
func (o *ShortenedURLPrefixDefault) WithPayload(payload *models.Error) *ShortenedURLPrefixDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the shortened URL prefix default response
func (o *ShortenedURLPrefixDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ShortenedURLPrefixDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
