// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MicahParks/terseurl/models"
)

// ShortenedSummaryOKCode is the HTTP code returned for type ShortenedSummaryOK
const ShortenedSummaryOKCode int = 200

/*ShortenedSummaryOK The map of shortened URLs to Terse summary data.

swagger:response shortenedSummaryOK
*/
type ShortenedSummaryOK struct {

	/*
	  In: Body
	*/
	Payload map[string]models.Summary `json:"body,omitempty"`
}

// NewShortenedSummaryOK creates ShortenedSummaryOK with default headers values
func NewShortenedSummaryOK() *ShortenedSummaryOK {

	return &ShortenedSummaryOK{}
}

// WithPayload adds the payload to the shortened summary o k response
func (o *ShortenedSummaryOK) WithPayload(payload map[string]models.Summary) *ShortenedSummaryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the shortened summary o k response
func (o *ShortenedSummaryOK) SetPayload(payload map[string]models.Summary) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ShortenedSummaryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty map
		payload = make(map[string]models.Summary, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*ShortenedSummaryDefault Unexpected error.

swagger:response shortenedSummaryDefault
*/
type ShortenedSummaryDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewShortenedSummaryDefault creates ShortenedSummaryDefault with default headers values
func NewShortenedSummaryDefault(code int) *ShortenedSummaryDefault {
	if code <= 0 {
		code = 500
	}

	return &ShortenedSummaryDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the shortened summary default response
func (o *ShortenedSummaryDefault) WithStatusCode(code int) *ShortenedSummaryDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the shortened summary default response
func (o *ShortenedSummaryDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the shortened summary default response
func (o *ShortenedSummaryDefault) WithPayload(payload *models.Error) *ShortenedSummaryDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the shortened summary default response
func (o *ShortenedSummaryDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ShortenedSummaryDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
