// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ShortenedDeleteHandlerFunc turns a function with the right signature into a shortened delete handler
type ShortenedDeleteHandlerFunc func(ShortenedDeleteParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ShortenedDeleteHandlerFunc) Handle(params ShortenedDeleteParams) middleware.Responder {
	return fn(params)
}

// ShortenedDeleteHandler interface for that can handle valid shortened delete params
type ShortenedDeleteHandler interface {
	Handle(ShortenedDeleteParams) middleware.Responder
}

// NewShortenedDelete creates a new http.Handler for the shortened delete operation
func NewShortenedDelete(ctx *middleware.Context, handler ShortenedDeleteHandler) *ShortenedDelete {
	return &ShortenedDelete{Context: ctx, Handler: handler}
}

/* ShortenedDelete swagger:route DELETE /api/terse api shortenedDelete

Delete all assets for the given shortened URLs.

Delete all assets for the given shortened URLs. This includes all Terse data, Visits data, and Summary data.

*/
type ShortenedDelete struct {
	Context *middleware.Context
	Handler ShortenedDeleteHandler
}

func (o *ShortenedDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewShortenedDeleteParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
