// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MicahParks/terseurl/models"
)

// ShortenedDeleteOKCode is the HTTP code returned for type ShortenedDeleteOK
const ShortenedDeleteOKCode int = 200

/*ShortenedDeleteOK The shortened URL's data was successfully deleted from the backend storage.

swagger:response shortenedDeleteOK
*/
type ShortenedDeleteOK struct {
}

// NewShortenedDeleteOK creates ShortenedDeleteOK with default headers values
func NewShortenedDeleteOK() *ShortenedDeleteOK {

	return &ShortenedDeleteOK{}
}

// WriteResponse to the client
func (o *ShortenedDeleteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*ShortenedDeleteDefault Unexpected error.

swagger:response shortenedDeleteDefault
*/
type ShortenedDeleteDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewShortenedDeleteDefault creates ShortenedDeleteDefault with default headers values
func NewShortenedDeleteDefault(code int) *ShortenedDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &ShortenedDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the shortened delete default response
func (o *ShortenedDeleteDefault) WithStatusCode(code int) *ShortenedDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the shortened delete default response
func (o *ShortenedDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the shortened delete default response
func (o *ShortenedDeleteDefault) WithPayload(payload *models.Error) *ShortenedDeleteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the shortened delete default response
func (o *ShortenedDeleteDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ShortenedDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
