// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MicahParks/terseurl/models"
)

// TerseImportOKCode is the HTTP code returned for type TerseImportOK
const TerseImportOKCode int = 200

/*TerseImportOK The import request was successfully fulfilled.

swagger:response terseImportOK
*/
type TerseImportOK struct {
}

// NewTerseImportOK creates TerseImportOK with default headers values
func NewTerseImportOK() *TerseImportOK {

	return &TerseImportOK{}
}

// WriteResponse to the client
func (o *TerseImportOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*TerseImportDefault Unexpected error.

swagger:response terseImportDefault
*/
type TerseImportDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewTerseImportDefault creates TerseImportDefault with default headers values
func NewTerseImportDefault(code int) *TerseImportDefault {
	if code <= 0 {
		code = 500
	}

	return &TerseImportDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the terse import default response
func (o *TerseImportDefault) WithStatusCode(code int) *TerseImportDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the terse import default response
func (o *TerseImportDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the terse import default response
func (o *TerseImportDefault) WithPayload(payload *models.Error) *TerseImportDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the terse import default response
func (o *TerseImportDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TerseImportDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
