// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MicahParks/terseurl/models"
)

// TerseSummaryOKCode is the HTTP code returned for type TerseSummaryOK
const TerseSummaryOKCode int = 200

/*TerseSummaryOK The map of shortened URLs to Terse summary data.

swagger:response terseSummaryOK
*/
type TerseSummaryOK struct {

	/*
	  In: Body
	*/
	Payload map[string]models.TerseSummary `json:"body,omitempty"`
}

// NewTerseSummaryOK creates TerseSummaryOK with default headers values
func NewTerseSummaryOK() *TerseSummaryOK {

	return &TerseSummaryOK{}
}

// WithPayload adds the payload to the terse summary o k response
func (o *TerseSummaryOK) WithPayload(payload map[string]models.TerseSummary) *TerseSummaryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the terse summary o k response
func (o *TerseSummaryOK) SetPayload(payload map[string]models.TerseSummary) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TerseSummaryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty map
		payload = make(map[string]models.TerseSummary, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*TerseSummaryDefault Unexpected error.

swagger:response terseSummaryDefault
*/
type TerseSummaryDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewTerseSummaryDefault creates TerseSummaryDefault with default headers values
func NewTerseSummaryDefault(code int) *TerseSummaryDefault {
	if code <= 0 {
		code = 500
	}

	return &TerseSummaryDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the terse summary default response
func (o *TerseSummaryDefault) WithStatusCode(code int) *TerseSummaryDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the terse summary default response
func (o *TerseSummaryDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the terse summary default response
func (o *TerseSummaryDefault) WithPayload(payload *models.Error) *TerseSummaryDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the terse summary default response
func (o *TerseSummaryDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TerseSummaryDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
