// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MicahParks/terseurl/models"
)

// TerseDeleteOneOKCode is the HTTP code returned for type TerseDeleteOneOK
const TerseDeleteOneOKCode int = 200

/*TerseDeleteOneOK The shortened URL's data was successfully deleted from the backend storage.

swagger:response terseDeleteOneOK
*/
type TerseDeleteOneOK struct {
}

// NewTerseDeleteOneOK creates TerseDeleteOneOK with default headers values
func NewTerseDeleteOneOK() *TerseDeleteOneOK {

	return &TerseDeleteOneOK{}
}

// WriteResponse to the client
func (o *TerseDeleteOneOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*TerseDeleteOneDefault Unexpected error.

swagger:response terseDeleteOneDefault
*/
type TerseDeleteOneDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewTerseDeleteOneDefault creates TerseDeleteOneDefault with default headers values
func NewTerseDeleteOneDefault(code int) *TerseDeleteOneDefault {
	if code <= 0 {
		code = 500
	}

	return &TerseDeleteOneDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the terse delete one default response
func (o *TerseDeleteOneDefault) WithStatusCode(code int) *TerseDeleteOneDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the terse delete one default response
func (o *TerseDeleteOneDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the terse delete one default response
func (o *TerseDeleteOneDefault) WithPayload(payload *models.Error) *TerseDeleteOneDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the terse delete one default response
func (o *TerseDeleteOneDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TerseDeleteOneDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
