// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// NewTerseReadParams creates a new TerseReadParams object
//
// There are no default values defined in the spec.
func NewTerseReadParams() TerseReadParams {

	return TerseReadParams{}
}

// TerseReadParams contains all the bound params for the terse read operation
// typically these are obtained from a http.Request
//
// swagger:parameters terseRead
type TerseReadParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The shortened URLs to read the Terse data for.
	  Required: true
	  In: body
	*/
	ShortenedURLs []string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewTerseReadParams() beforehand.
func (o *TerseReadParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body []string
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("shortenedURLs", "body", ""))
			} else {
				res = append(res, errors.NewParseError("shortenedURLs", "body", "", err))
			}
		} else {
			// no validation required on inline body
			o.ShortenedURLs = body
		}
	} else {
		res = append(res, errors.Required("shortenedURLs", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
