// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MicahParks/terseurl/models"
)

// TerseDeleteSomeOKCode is the HTTP code returned for type TerseDeleteSomeOK
const TerseDeleteSomeOKCode int = 200

/*TerseDeleteSomeOK The shortened URL's data was successfully deleted from the backend storage.

swagger:response terseDeleteSomeOK
*/
type TerseDeleteSomeOK struct {
}

// NewTerseDeleteSomeOK creates TerseDeleteSomeOK with default headers values
func NewTerseDeleteSomeOK() *TerseDeleteSomeOK {

	return &TerseDeleteSomeOK{}
}

// WriteResponse to the client
func (o *TerseDeleteSomeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*TerseDeleteSomeDefault Unexpected error.

swagger:response terseDeleteSomeDefault
*/
type TerseDeleteSomeDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewTerseDeleteSomeDefault creates TerseDeleteSomeDefault with default headers values
func NewTerseDeleteSomeDefault(code int) *TerseDeleteSomeDefault {
	if code <= 0 {
		code = 500
	}

	return &TerseDeleteSomeDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the terse delete some default response
func (o *TerseDeleteSomeDefault) WithStatusCode(code int) *TerseDeleteSomeDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the terse delete some default response
func (o *TerseDeleteSomeDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the terse delete some default response
func (o *TerseDeleteSomeDefault) WithPayload(payload *models.Error) *TerseDeleteSomeDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the terse delete some default response
func (o *TerseDeleteSomeDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TerseDeleteSomeDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
