// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// TerseTerseHandlerFunc turns a function with the right signature into a terse terse handler
type TerseTerseHandlerFunc func(TerseTerseParams) middleware.Responder

// Handle executing the request and returning a response
func (fn TerseTerseHandlerFunc) Handle(params TerseTerseParams) middleware.Responder {
	return fn(params)
}

// TerseTerseHandler interface for that can handle valid terse terse params
type TerseTerseHandler interface {
	Handle(TerseTerseParams) middleware.Responder
}

// NewTerseTerse creates a new http.Handler for the terse terse operation
func NewTerseTerse(ctx *middleware.Context, handler TerseTerseHandler) *TerseTerse {
	return &TerseTerse{Context: ctx, Handler: handler}
}

/*TerseTerse swagger:route GET /api/terse/{shortened} api terseTerse

Read the Terse data for the given shortened URL.

*/
type TerseTerse struct {
	Context *middleware.Context
	Handler TerseTerseHandler
}

func (o *TerseTerse) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewTerseTerseParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
