// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MicahParks/terse-URL/models"
)

// TerseExportOKCode is the HTTP code returned for type TerseExportOK
const TerseExportOKCode int = 200

/*TerseExportOK The export was successfully retrieved.

swagger:response terseExportOK
*/
type TerseExportOK struct {

	/*All of the Terse and Visit data from the backend.
	  In: Body
	*/
	Payload map[string]models.Export `json:"body,omitempty"`
}

// NewTerseExportOK creates TerseExportOK with default headers values
func NewTerseExportOK() *TerseExportOK {

	return &TerseExportOK{}
}

// WithPayload adds the payload to the terse export o k response
func (o *TerseExportOK) WithPayload(payload map[string]models.Export) *TerseExportOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the terse export o k response
func (o *TerseExportOK) SetPayload(payload map[string]models.Export) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TerseExportOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty map
		payload = make(map[string]models.Export, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*TerseExportDefault Unexpected error.

swagger:response terseExportDefault
*/
type TerseExportDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewTerseExportDefault creates TerseExportDefault with default headers values
func NewTerseExportDefault(code int) *TerseExportDefault {
	if code <= 0 {
		code = 500
	}

	return &TerseExportDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the terse export default response
func (o *TerseExportDefault) WithStatusCode(code int) *TerseExportDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the terse export default response
func (o *TerseExportDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the terse export default response
func (o *TerseExportDefault) WithPayload(payload *models.Error) *TerseExportDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the terse export default response
func (o *TerseExportDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TerseExportDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
