// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// VisitsReadHandlerFunc turns a function with the right signature into a visits read handler
type VisitsReadHandlerFunc func(VisitsReadParams) middleware.Responder

// Handle executing the request and returning a response
func (fn VisitsReadHandlerFunc) Handle(params VisitsReadParams) middleware.Responder {
	return fn(params)
}

// VisitsReadHandler interface for that can handle valid visits read params
type VisitsReadHandler interface {
	Handle(VisitsReadParams) middleware.Responder
}

// NewVisitsRead creates a new http.Handler for the visits read operation
func NewVisitsRead(ctx *middleware.Context, handler VisitsReadHandler) *VisitsRead {
	return &VisitsRead{Context: ctx, Handler: handler}
}

/* VisitsRead swagger:route POST /api/visits api visitsRead

Read the Visits data for the given shortened URLs.

Read the Visits data for the given shortened URLs.

*/
type VisitsRead struct {
	Context *middleware.Context
	Handler VisitsReadHandler
}

func (o *VisitsRead) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewVisitsReadParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
