// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MicahParks/terseurl/models"
)

// VisitsDeleteOKCode is the HTTP code returned for type VisitsDeleteOK
const VisitsDeleteOKCode int = 200

/*VisitsDeleteOK The shortened URL's Visits data was successfully deleted from the backend storage.

swagger:response visitsDeleteOK
*/
type VisitsDeleteOK struct {
}

// NewVisitsDeleteOK creates VisitsDeleteOK with default headers values
func NewVisitsDeleteOK() *VisitsDeleteOK {

	return &VisitsDeleteOK{}
}

// WriteResponse to the client
func (o *VisitsDeleteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*VisitsDeleteDefault Unexpected error.

swagger:response visitsDeleteDefault
*/
type VisitsDeleteDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewVisitsDeleteDefault creates VisitsDeleteDefault with default headers values
func NewVisitsDeleteDefault(code int) *VisitsDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &VisitsDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the visits delete default response
func (o *VisitsDeleteDefault) WithStatusCode(code int) *VisitsDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the visits delete default response
func (o *VisitsDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the visits delete default response
func (o *VisitsDeleteDefault) WithPayload(payload *models.Error) *VisitsDeleteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the visits delete default response
func (o *VisitsDeleteDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VisitsDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
