// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/MicahParks/terseurl/models"
)

// VisitsDeleteHandlerFunc turns a function with the right signature into a visits delete handler
type VisitsDeleteHandlerFunc func(VisitsDeleteParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn VisitsDeleteHandlerFunc) Handle(params VisitsDeleteParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// VisitsDeleteHandler interface for that can handle valid visits delete params
type VisitsDeleteHandler interface {
	Handle(VisitsDeleteParams, *models.Principal) middleware.Responder
}

// NewVisitsDelete creates a new http.Handler for the visits delete operation
func NewVisitsDelete(ctx *middleware.Context, handler VisitsDeleteHandler) *VisitsDelete {
	return &VisitsDelete{Context: ctx, Handler: handler}
}

/* VisitsDelete swagger:route DELETE /api/visits api visitsDelete

Delete all Visits data for the given shortened URLs.

Delete all Visits data for the given shortened URLs. This will affect Summary data.

*/
type VisitsDelete struct {
	Context *middleware.Context
	Handler VisitsDeleteHandler
}

func (o *VisitsDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewVisitsDeleteParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
