// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MicahParks/terseurl/models"
)

// VisitsReadOKCode is the HTTP code returned for type VisitsReadOK
const VisitsReadOKCode int = 200

/*VisitsReadOK The Visits data was successfully retrieved.

swagger:response visitsReadOK
*/
type VisitsReadOK struct {

	/*
	  In: Body
	*/
	Payload map[string][]models.Visit `json:"body,omitempty"`
}

// NewVisitsReadOK creates VisitsReadOK with default headers values
func NewVisitsReadOK() *VisitsReadOK {

	return &VisitsReadOK{}
}

// WithPayload adds the payload to the visits read o k response
func (o *VisitsReadOK) WithPayload(payload map[string][]models.Visit) *VisitsReadOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the visits read o k response
func (o *VisitsReadOK) SetPayload(payload map[string][]models.Visit) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VisitsReadOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty map
		payload = make(map[string][]models.Visit, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*VisitsReadDefault Unexpected error.

swagger:response visitsReadDefault
*/
type VisitsReadDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewVisitsReadDefault creates VisitsReadDefault with default headers values
func NewVisitsReadDefault(code int) *VisitsReadDefault {
	if code <= 0 {
		code = 500
	}

	return &VisitsReadDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the visits read default response
func (o *VisitsReadDefault) WithStatusCode(code int) *VisitsReadDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the visits read default response
func (o *VisitsReadDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the visits read default response
func (o *VisitsReadDefault) WithPayload(payload *models.Error) *VisitsReadDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the visits read default response
func (o *VisitsReadDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VisitsReadDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
