version: "3"
services:
  caddy:
    container_name: "caddy"
    image: "caddy:2"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./frontend:/frontend/frontend" # This is because of how Caddy translates paths in the root directive.
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "caddy:/data"
      - "caddyConfig:/config"
  terseurl:
    build:
      context: "."
      dockerfile: "Dockerfile"
    container_name: "terseurl"
    image: "micahparks/terseurl"
    volumes:
      - "./terseStore.json:/terseStore.json:ro"
      - "./terse.bbolt:/terse.bbolt"
      - "./visitsStore.json:/visitsStore.json:ro"
      - "./visits.bbolt:/visits.bbolt"
      - "./socialMediaLinkPreview.gohtml:/socialMediaLinkPreview.gohtml"
volumes:
  caddy:
  caddyConfig:
