version: "3"
services:
  caddy:
    container_name: "caddy"
    image: "caddy:2"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./frontend:/frontend/frontend" # This is because of how Caddy translates paths in the root directive.
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "caddy:/data"
      - "caddyConfig:/config"
  terseurl:
    build:
      context: "."
      dockerfile: "Dockerfile"
    container_name: "terseurl"
    image: "micahparks/terseurl"
    volumes:
      - "./terseStore.json:/terseurl/terseStore.json:ro"
      - "./terse.bbolt:/terseurl/terse.bbolt"
      - "./visitsStore.json:/terseurl/visitsStore.json:ro"
      - "./visits.bbolt:/terseurl/visits.bbolt"
      - "./redirect.gohtml:/terseurl/redirect.gohtml"
volumes:
  caddy:
  caddyConfig:
