// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MicahParks/terse-URL/models"
)

// FrontendOKCode is the HTTP code returned for type FrontendOK
const FrontendOKCode int = 200

/*FrontendOK The frontend asset.

swagger:response frontendOK
*/
type FrontendOK struct {

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewFrontendOK creates FrontendOK with default headers values
func NewFrontendOK() *FrontendOK {

	return &FrontendOK{}
}

// WithPayload adds the payload to the frontend o k response
func (o *FrontendOK) WithPayload(payload io.ReadCloser) *FrontendOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the frontend o k response
func (o *FrontendOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FrontendOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// FrontendNotFoundCode is the HTTP code returned for type FrontendNotFound
const FrontendNotFoundCode int = 404

/*FrontendNotFound The requested asset was not found.

swagger:response frontendNotFound
*/
type FrontendNotFound struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewFrontendNotFound creates FrontendNotFound with default headers values
func NewFrontendNotFound() *FrontendNotFound {

	return &FrontendNotFound{}
}

// WithPayload adds the payload to the frontend not found response
func (o *FrontendNotFound) WithPayload(payload string) *FrontendNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the frontend not found response
func (o *FrontendNotFound) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FrontendNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*FrontendDefault Unexpected error.

swagger:response frontendDefault
*/
type FrontendDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFrontendDefault creates FrontendDefault with default headers values
func NewFrontendDefault(code int) *FrontendDefault {
	if code <= 0 {
		code = 500
	}

	return &FrontendDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the frontend default response
func (o *FrontendDefault) WithStatusCode(code int) *FrontendDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the frontend default response
func (o *FrontendDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the frontend default response
func (o *FrontendDefault) WithPayload(payload *models.Error) *FrontendDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the frontend default response
func (o *FrontendDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FrontendDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
