// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MicahParks/terse-URL/models"
)

// TerseDumpShortenedOKCode is the HTTP code returned for type TerseDumpShortenedOK
const TerseDumpShortenedOKCode int = 200

/*TerseDumpShortenedOK terse dump shortened o k

swagger:response terseDumpShortenedOK
*/
type TerseDumpShortenedOK struct {

	/*
	  In: Body
	*/
	Payload *models.Dump `json:"body,omitempty"`
}

// NewTerseDumpShortenedOK creates TerseDumpShortenedOK with default headers values
func NewTerseDumpShortenedOK() *TerseDumpShortenedOK {

	return &TerseDumpShortenedOK{}
}

// WithPayload adds the payload to the terse dump shortened o k response
func (o *TerseDumpShortenedOK) WithPayload(payload *models.Dump) *TerseDumpShortenedOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the terse dump shortened o k response
func (o *TerseDumpShortenedOK) SetPayload(payload *models.Dump) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TerseDumpShortenedOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*TerseDumpShortenedDefault Unexpected error.

swagger:response terseDumpShortenedDefault
*/
type TerseDumpShortenedDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewTerseDumpShortenedDefault creates TerseDumpShortenedDefault with default headers values
func NewTerseDumpShortenedDefault(code int) *TerseDumpShortenedDefault {
	if code <= 0 {
		code = 500
	}

	return &TerseDumpShortenedDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the terse dump shortened default response
func (o *TerseDumpShortenedDefault) WithStatusCode(code int) *TerseDumpShortenedDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the terse dump shortened default response
func (o *TerseDumpShortenedDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the terse dump shortened default response
func (o *TerseDumpShortenedDefault) WithPayload(payload *models.Error) *TerseDumpShortenedDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the terse dump shortened default response
func (o *TerseDumpShortenedDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TerseDumpShortenedDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
