// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/MicahParks/terse-URL/models"
)

// TerseDeleteHandlerFunc turns a function with the right signature into a terse delete handler
type TerseDeleteHandlerFunc func(TerseDeleteParams, *models.JWTInfo) middleware.Responder

// Handle executing the request and returning a response
func (fn TerseDeleteHandlerFunc) Handle(params TerseDeleteParams, principal *models.JWTInfo) middleware.Responder {
	return fn(params, principal)
}

// TerseDeleteHandler interface for that can handle valid terse delete params
type TerseDeleteHandler interface {
	Handle(TerseDeleteParams, *models.JWTInfo) middleware.Responder
}

// NewTerseDelete creates a new http.Handler for the terse delete operation
func NewTerseDelete(ctx *middleware.Context, handler TerseDeleteHandler) *TerseDelete {
	return &TerseDelete{Context: ctx, Handler: handler}
}

/*TerseDelete swagger:route DELETE /api/delete terseDelete

Delete the given shortened URL from the backend storage, cause the shortened URL to immediately expire.

*/
type TerseDelete struct {
	Context *middleware.Context
	Handler TerseDeleteHandler
}

func (o *TerseDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewTerseDeleteParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.JWTInfo
	if uprinc != nil {
		principal = uprinc.(*models.JWTInfo) // this is really a models.JWTInfo, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
