// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	apiops "github.com/MicahParks/terseurl/restapi/operations/api"
	"github.com/MicahParks/terseurl/restapi/operations/public"
	"github.com/MicahParks/terseurl/restapi/operations/system"
)

// NewTerseurlAPI creates a new Terseurl instance
func NewTerseurlAPI(spec *loads.Document) *TerseurlAPI {
	return &TerseurlAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		HTMLProducer: runtime.ProducerFunc(func(w io.Writer, data interface{}) error {
			return errors.NotImplemented("html producer has not yet been implemented")
		}),
		JSONProducer: runtime.JSONProducer(),

		SystemAliveHandler: system.AliveHandlerFunc(func(params system.AliveParams) middleware.Responder {
			return middleware.NotImplemented("operation system.Alive has not yet been implemented")
		}),
		APIFrontendMetaHandler: apiops.FrontendMetaHandlerFunc(func(params apiops.FrontendMetaParams) middleware.Responder {
			return middleware.NotImplemented("operation api.FrontendMeta has not yet been implemented")
		}),
		APITerseDeleteHandler: apiops.TerseDeleteHandlerFunc(func(params apiops.TerseDeleteParams) middleware.Responder {
			return middleware.NotImplemented("operation api.TerseDelete has not yet been implemented")
		}),
		APITerseDeleteSomeHandler: apiops.TerseDeleteSomeHandlerFunc(func(params apiops.TerseDeleteSomeParams) middleware.Responder {
			return middleware.NotImplemented("operation api.TerseDeleteSome has not yet been implemented")
		}),
		APITerseExportHandler: apiops.TerseExportHandlerFunc(func(params apiops.TerseExportParams) middleware.Responder {
			return middleware.NotImplemented("operation api.TerseExport has not yet been implemented")
		}),
		APITerseExportSomeHandler: apiops.TerseExportSomeHandlerFunc(func(params apiops.TerseExportSomeParams) middleware.Responder {
			return middleware.NotImplemented("operation api.TerseExportSome has not yet been implemented")
		}),
		APITerseImportHandler: apiops.TerseImportHandlerFunc(func(params apiops.TerseImportParams) middleware.Responder {
			return middleware.NotImplemented("operation api.TerseImport has not yet been implemented")
		}),
		APITersePrefixHandler: apiops.TersePrefixHandlerFunc(func(params apiops.TersePrefixParams) middleware.Responder {
			return middleware.NotImplemented("operation api.TersePrefix has not yet been implemented")
		}),
		PublicTerseRedirectHandler: public.TerseRedirectHandlerFunc(func(params public.TerseRedirectParams) middleware.Responder {
			return middleware.NotImplemented("operation public.TerseRedirect has not yet been implemented")
		}),
		APITerseSummaryHandler: apiops.TerseSummaryHandlerFunc(func(params apiops.TerseSummaryParams) middleware.Responder {
			return middleware.NotImplemented("operation api.TerseSummary has not yet been implemented")
		}),
		APITerseTerseHandler: apiops.TerseTerseHandlerFunc(func(params apiops.TerseTerseParams) middleware.Responder {
			return middleware.NotImplemented("operation api.TerseTerse has not yet been implemented")
		}),
		APITerseVisitsHandler: apiops.TerseVisitsHandlerFunc(func(params apiops.TerseVisitsParams) middleware.Responder {
			return middleware.NotImplemented("operation api.TerseVisits has not yet been implemented")
		}),
		APITerseWriteHandler: apiops.TerseWriteHandlerFunc(func(params apiops.TerseWriteParams) middleware.Responder {
			return middleware.NotImplemented("operation api.TerseWrite has not yet been implemented")
		}),
	}
}

/*TerseurlAPI The Terse URL shortener. */
type TerseurlAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// HTMLProducer registers a producer for the following mime types:
	//   - text/html
	HTMLProducer runtime.Producer
	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// SystemAliveHandler sets the operation handler for the alive operation
	SystemAliveHandler system.AliveHandler
	// APIFrontendMetaHandler sets the operation handler for the frontend meta operation
	APIFrontendMetaHandler apiops.FrontendMetaHandler
	// APITerseDeleteHandler sets the operation handler for the terse delete operation
	APITerseDeleteHandler apiops.TerseDeleteHandler
	// APITerseDeleteSomeHandler sets the operation handler for the terse delete some operation
	APITerseDeleteSomeHandler apiops.TerseDeleteSomeHandler
	// APITerseExportHandler sets the operation handler for the terse export operation
	APITerseExportHandler apiops.TerseExportHandler
	// APITerseExportSomeHandler sets the operation handler for the terse export some operation
	APITerseExportSomeHandler apiops.TerseExportSomeHandler
	// APITerseImportHandler sets the operation handler for the terse import operation
	APITerseImportHandler apiops.TerseImportHandler
	// APITersePrefixHandler sets the operation handler for the terse prefix operation
	APITersePrefixHandler apiops.TersePrefixHandler
	// PublicTerseRedirectHandler sets the operation handler for the terse redirect operation
	PublicTerseRedirectHandler public.TerseRedirectHandler
	// APITerseSummaryHandler sets the operation handler for the terse summary operation
	APITerseSummaryHandler apiops.TerseSummaryHandler
	// APITerseTerseHandler sets the operation handler for the terse terse operation
	APITerseTerseHandler apiops.TerseTerseHandler
	// APITerseVisitsHandler sets the operation handler for the terse visits operation
	APITerseVisitsHandler apiops.TerseVisitsHandler
	// APITerseWriteHandler sets the operation handler for the terse write operation
	APITerseWriteHandler apiops.TerseWriteHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *TerseurlAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *TerseurlAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *TerseurlAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *TerseurlAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *TerseurlAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *TerseurlAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *TerseurlAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *TerseurlAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *TerseurlAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the TerseurlAPI
func (o *TerseurlAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.HTMLProducer == nil {
		unregistered = append(unregistered, "HTMLProducer")
	}
	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.SystemAliveHandler == nil {
		unregistered = append(unregistered, "system.AliveHandler")
	}
	if o.APIFrontendMetaHandler == nil {
		unregistered = append(unregistered, "api.FrontendMetaHandler")
	}
	if o.APITerseDeleteHandler == nil {
		unregistered = append(unregistered, "api.TerseDeleteHandler")
	}
	if o.APITerseDeleteSomeHandler == nil {
		unregistered = append(unregistered, "api.TerseDeleteSomeHandler")
	}
	if o.APITerseExportHandler == nil {
		unregistered = append(unregistered, "api.TerseExportHandler")
	}
	if o.APITerseExportSomeHandler == nil {
		unregistered = append(unregistered, "api.TerseExportSomeHandler")
	}
	if o.APITerseImportHandler == nil {
		unregistered = append(unregistered, "api.TerseImportHandler")
	}
	if o.APITersePrefixHandler == nil {
		unregistered = append(unregistered, "api.TersePrefixHandler")
	}
	if o.PublicTerseRedirectHandler == nil {
		unregistered = append(unregistered, "public.TerseRedirectHandler")
	}
	if o.APITerseSummaryHandler == nil {
		unregistered = append(unregistered, "api.TerseSummaryHandler")
	}
	if o.APITerseTerseHandler == nil {
		unregistered = append(unregistered, "api.TerseTerseHandler")
	}
	if o.APITerseVisitsHandler == nil {
		unregistered = append(unregistered, "api.TerseVisitsHandler")
	}
	if o.APITerseWriteHandler == nil {
		unregistered = append(unregistered, "api.TerseWriteHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *TerseurlAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *TerseurlAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *TerseurlAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *TerseurlAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *TerseurlAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "text/html":
			result["text/html"] = o.HTMLProducer
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *TerseurlAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the terseurl API
func (o *TerseurlAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *TerseurlAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/alive"] = system.NewAlive(o.context, o.SystemAliveHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/frontend/meta"] = apiops.NewFrontendMeta(o.context, o.APIFrontendMetaHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/api/delete"] = apiops.NewTerseDelete(o.context, o.APITerseDeleteHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/api/delete/some"] = apiops.NewTerseDeleteSome(o.context, o.APITerseDeleteSomeHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/export"] = apiops.NewTerseExport(o.context, o.APITerseExportHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/export/some"] = apiops.NewTerseExportSome(o.context, o.APITerseExportSomeHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/import"] = apiops.NewTerseImport(o.context, o.APITerseImportHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/prefix"] = apiops.NewTersePrefix(o.context, o.APITersePrefixHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/{shortened}"] = public.NewTerseRedirect(o.context, o.PublicTerseRedirectHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/summary"] = apiops.NewTerseSummary(o.context, o.APITerseSummaryHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/terse/{shortened}"] = apiops.NewTerseTerse(o.context, o.APITerseTerseHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/visits/{shortened}"] = apiops.NewTerseVisits(o.context, o.APITerseVisitsHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/write/{operation}"] = apiops.NewTerseWrite(o.context, o.APITerseWriteHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *TerseurlAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *TerseurlAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *TerseurlAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *TerseurlAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *TerseurlAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
