// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/MicahParks/terseurl/models"
	apiops "github.com/MicahParks/terseurl/restapi/operations/api"
	"github.com/MicahParks/terseurl/restapi/operations/public"
	"github.com/MicahParks/terseurl/restapi/operations/system"
)

// NewTerseurlAPI creates a new Terseurl instance
func NewTerseurlAPI(spec *loads.Document) *TerseurlAPI {
	return &TerseurlAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		HTMLProducer: runtime.ProducerFunc(func(w io.Writer, data interface{}) error {
			return errors.NotImplemented("html producer has not yet been implemented")
		}),
		JSONProducer: runtime.JSONProducer(),

		APIExportHandler: apiops.ExportHandlerFunc(func(params apiops.ExportParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation api.Export has not yet been implemented")
		}),
		APIFrontendMetaHandler: apiops.FrontendMetaHandlerFunc(func(params apiops.FrontendMetaParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation api.FrontendMeta has not yet been implemented")
		}),
		APIImportHandler: apiops.ImportHandlerFunc(func(params apiops.ImportParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation api.Import has not yet been implemented")
		}),
		PublicPublicRedirectHandler: public.PublicRedirectHandlerFunc(func(params public.PublicRedirectParams) middleware.Responder {
			return middleware.NotImplemented("operation public.PublicRedirect has not yet been implemented")
		}),
		APIShortenedDeleteHandler: apiops.ShortenedDeleteHandlerFunc(func(params apiops.ShortenedDeleteParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation api.ShortenedDelete has not yet been implemented")
		}),
		APIShortenedPrefixHandler: apiops.ShortenedPrefixHandlerFunc(func(params apiops.ShortenedPrefixParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation api.ShortenedPrefix has not yet been implemented")
		}),
		APIShortenedSummaryHandler: apiops.ShortenedSummaryHandlerFunc(func(params apiops.ShortenedSummaryParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation api.ShortenedSummary has not yet been implemented")
		}),
		SystemSystemAliveHandler: system.SystemAliveHandlerFunc(func(params system.SystemAliveParams) middleware.Responder {
			return middleware.NotImplemented("operation system.SystemAlive has not yet been implemented")
		}),
		APITerseReadHandler: apiops.TerseReadHandlerFunc(func(params apiops.TerseReadParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation api.TerseRead has not yet been implemented")
		}),
		APITerseWriteHandler: apiops.TerseWriteHandlerFunc(func(params apiops.TerseWriteParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation api.TerseWrite has not yet been implemented")
		}),
		APIVisitsDeleteHandler: apiops.VisitsDeleteHandlerFunc(func(params apiops.VisitsDeleteParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation api.VisitsDelete has not yet been implemented")
		}),
		APIVisitsReadHandler: apiops.VisitsReadHandlerFunc(func(params apiops.VisitsReadParams, principal *models.Principal) middleware.Responder {
			return middleware.NotImplemented("operation api.VisitsRead has not yet been implemented")
		}),

		// Applies when the "Authorization" header is set
		JWTAuth: func(token string) (*models.Principal, error) {
			return nil, errors.NotImplemented("api key auth (JWT) Authorization from header param [Authorization] has not yet been implemented")
		},
		// default authorizer is authorized meaning no requests are blocked
		APIAuthorizer: security.Authorized(),
	}
}

/*TerseurlAPI The Terse URL shortener. */
type TerseurlAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// HTMLProducer registers a producer for the following mime types:
	//   - text/html
	HTMLProducer runtime.Producer
	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// JWTAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key Authorization provided in the header
	JWTAuth func(string) (*models.Principal, error)

	// APIAuthorizer provides access control (ACL/RBAC/ABAC) by providing access to the request and authenticated principal
	APIAuthorizer runtime.Authorizer

	// APIExportHandler sets the operation handler for the export operation
	APIExportHandler apiops.ExportHandler
	// APIFrontendMetaHandler sets the operation handler for the frontend meta operation
	APIFrontendMetaHandler apiops.FrontendMetaHandler
	// APIImportHandler sets the operation handler for the import operation
	APIImportHandler apiops.ImportHandler
	// PublicPublicRedirectHandler sets the operation handler for the public redirect operation
	PublicPublicRedirectHandler public.PublicRedirectHandler
	// APIShortenedDeleteHandler sets the operation handler for the shortened delete operation
	APIShortenedDeleteHandler apiops.ShortenedDeleteHandler
	// APIShortenedPrefixHandler sets the operation handler for the shortened prefix operation
	APIShortenedPrefixHandler apiops.ShortenedPrefixHandler
	// APIShortenedSummaryHandler sets the operation handler for the shortened summary operation
	APIShortenedSummaryHandler apiops.ShortenedSummaryHandler
	// SystemSystemAliveHandler sets the operation handler for the system alive operation
	SystemSystemAliveHandler system.SystemAliveHandler
	// APITerseReadHandler sets the operation handler for the terse read operation
	APITerseReadHandler apiops.TerseReadHandler
	// APITerseWriteHandler sets the operation handler for the terse write operation
	APITerseWriteHandler apiops.TerseWriteHandler
	// APIVisitsDeleteHandler sets the operation handler for the visits delete operation
	APIVisitsDeleteHandler apiops.VisitsDeleteHandler
	// APIVisitsReadHandler sets the operation handler for the visits read operation
	APIVisitsReadHandler apiops.VisitsReadHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *TerseurlAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *TerseurlAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *TerseurlAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *TerseurlAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *TerseurlAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *TerseurlAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *TerseurlAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *TerseurlAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *TerseurlAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the TerseurlAPI
func (o *TerseurlAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.HTMLProducer == nil {
		unregistered = append(unregistered, "HTMLProducer")
	}
	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.JWTAuth == nil {
		unregistered = append(unregistered, "AuthorizationAuth")
	}

	if o.APIExportHandler == nil {
		unregistered = append(unregistered, "api.ExportHandler")
	}
	if o.APIFrontendMetaHandler == nil {
		unregistered = append(unregistered, "api.FrontendMetaHandler")
	}
	if o.APIImportHandler == nil {
		unregistered = append(unregistered, "api.ImportHandler")
	}
	if o.PublicPublicRedirectHandler == nil {
		unregistered = append(unregistered, "public.PublicRedirectHandler")
	}
	if o.APIShortenedDeleteHandler == nil {
		unregistered = append(unregistered, "api.ShortenedDeleteHandler")
	}
	if o.APIShortenedPrefixHandler == nil {
		unregistered = append(unregistered, "api.ShortenedPrefixHandler")
	}
	if o.APIShortenedSummaryHandler == nil {
		unregistered = append(unregistered, "api.ShortenedSummaryHandler")
	}
	if o.SystemSystemAliveHandler == nil {
		unregistered = append(unregistered, "system.SystemAliveHandler")
	}
	if o.APITerseReadHandler == nil {
		unregistered = append(unregistered, "api.TerseReadHandler")
	}
	if o.APITerseWriteHandler == nil {
		unregistered = append(unregistered, "api.TerseWriteHandler")
	}
	if o.APIVisitsDeleteHandler == nil {
		unregistered = append(unregistered, "api.VisitsDeleteHandler")
	}
	if o.APIVisitsReadHandler == nil {
		unregistered = append(unregistered, "api.VisitsReadHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *TerseurlAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *TerseurlAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	result := make(map[string]runtime.Authenticator)
	for name := range schemes {
		switch name {
		case "JWT":
			scheme := schemes[name]
			result[name] = o.APIKeyAuthenticator(scheme.Name, scheme.In, func(token string) (interface{}, error) {
				return o.JWTAuth(token)
			})

		}
	}
	return result
}

// Authorizer returns the registered authorizer
func (o *TerseurlAPI) Authorizer() runtime.Authorizer {
	return o.APIAuthorizer
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *TerseurlAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *TerseurlAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "text/html":
			result["text/html"] = o.HTMLProducer
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *TerseurlAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the terseurl API
func (o *TerseurlAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *TerseurlAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/export"] = apiops.NewExport(o.context, o.APIExportHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/frontend/meta"] = apiops.NewFrontendMeta(o.context, o.APIFrontendMetaHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/import"] = apiops.NewImport(o.context, o.APIImportHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/{shortenedURL}"] = public.NewPublicRedirect(o.context, o.PublicPublicRedirectHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/api/shortened"] = apiops.NewShortenedDelete(o.context, o.APIShortenedDeleteHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/prefix"] = apiops.NewShortenedPrefix(o.context, o.APIShortenedPrefixHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/summary"] = apiops.NewShortenedSummary(o.context, o.APIShortenedSummaryHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/alive"] = system.NewSystemAlive(o.context, o.SystemSystemAliveHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/terse"] = apiops.NewTerseRead(o.context, o.APITerseReadHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/write/{operation}"] = apiops.NewTerseWrite(o.context, o.APITerseWriteHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/api/visits"] = apiops.NewVisitsDelete(o.context, o.APIVisitsDeleteHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/visits"] = apiops.NewVisitsRead(o.context, o.APIVisitsReadHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *TerseurlAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *TerseurlAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *TerseurlAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *TerseurlAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *TerseurlAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
