// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// TerseRedirectFoundCode is the HTTP code returned for type TerseRedirectFound
const TerseRedirectFoundCode int = 302

/*TerseRedirectFound The shortened URL to visit that will redirect to the given full URL.

swagger:response terseRedirectFound
*/
type TerseRedirectFound struct {
	/*The full URL that the redirect leads to.

	 */
	Location string `json:"Location"`
}

// NewTerseRedirectFound creates TerseRedirectFound with default headers values
func NewTerseRedirectFound() *TerseRedirectFound {

	return &TerseRedirectFound{}
}

// WithLocation adds the location to the terse redirect found response
func (o *TerseRedirectFound) WithLocation(location string) *TerseRedirectFound {
	o.Location = location
	return o
}

// SetLocation sets the location to the terse redirect found response
func (o *TerseRedirectFound) SetLocation(location string) {
	o.Location = location
}

// WriteResponse to the client
func (o *TerseRedirectFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Location

	location := o.Location
	if location != "" {
		rw.Header().Set("Location", location)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(302)
}

// TerseRedirectNotFoundCode is the HTTP code returned for type TerseRedirectNotFound
const TerseRedirectNotFoundCode int = 404

/*TerseRedirectNotFound The shortened URL expired or never existed.

swagger:response terseRedirectNotFound
*/
type TerseRedirectNotFound struct {
}

// NewTerseRedirectNotFound creates TerseRedirectNotFound with default headers values
func NewTerseRedirectNotFound() *TerseRedirectNotFound {

	return &TerseRedirectNotFound{}
}

// WriteResponse to the client
func (o *TerseRedirectNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
