// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/MicahParks/terse-URL/models"
)

// URLNewHandlerFunc turns a function with the right signature into a url new handler
type URLNewHandlerFunc func(URLNewParams, *models.JWTInfo) middleware.Responder

// Handle executing the request and returning a response
func (fn URLNewHandlerFunc) Handle(params URLNewParams, principal *models.JWTInfo) middleware.Responder {
	return fn(params, principal)
}

// URLNewHandler interface for that can handle valid url new params
type URLNewHandler interface {
	Handle(URLNewParams, *models.JWTInfo) middleware.Responder
}

// NewURLNew creates a new http.Handler for the url new operation
func NewURLNew(ctx *middleware.Context, handler URLNewHandler) *URLNew {
	return &URLNew{Context: ctx, Handler: handler}
}

/*URLNew swagger:route POST /api/new urlNew

URLNew url new API

*/
type URLNew struct {
	Context *middleware.Context
	Handler URLNewHandler
}

func (o *URLNew) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewURLNewParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.JWTInfo
	if uprinc != nil {
		principal = uprinc.(*models.JWTInfo) // this is really a models.JWTInfo, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
