// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MicahParks/terse-URL/models"
)

// URLDumpShortenedOKCode is the HTTP code returned for type URLDumpShortenedOK
const URLDumpShortenedOKCode int = 200

/*URLDumpShortenedOK url dump shortened o k

swagger:response urlDumpShortenedOK
*/
type URLDumpShortenedOK struct {

	/*
	  In: Body
	*/
	Payload *models.Dump `json:"body,omitempty"`
}

// NewURLDumpShortenedOK creates URLDumpShortenedOK with default headers values
func NewURLDumpShortenedOK() *URLDumpShortenedOK {

	return &URLDumpShortenedOK{}
}

// WithPayload adds the payload to the url dump shortened o k response
func (o *URLDumpShortenedOK) WithPayload(payload *models.Dump) *URLDumpShortenedOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the url dump shortened o k response
func (o *URLDumpShortenedOK) SetPayload(payload *models.Dump) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *URLDumpShortenedOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*URLDumpShortenedDefault Unexpected error.

swagger:response urlDumpShortenedDefault
*/
type URLDumpShortenedDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewURLDumpShortenedDefault creates URLDumpShortenedDefault with default headers values
func NewURLDumpShortenedDefault(code int) *URLDumpShortenedDefault {
	if code <= 0 {
		code = 500
	}

	return &URLDumpShortenedDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the url dump shortened default response
func (o *URLDumpShortenedDefault) WithStatusCode(code int) *URLDumpShortenedDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the url dump shortened default response
func (o *URLDumpShortenedDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the url dump shortened default response
func (o *URLDumpShortenedDefault) WithPayload(payload *models.Error) *URLDumpShortenedDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the url dump shortened default response
func (o *URLDumpShortenedDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *URLDumpShortenedDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
