// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// URLGetFoundCode is the HTTP code returned for type URLGetFound
const URLGetFoundCode int = 302

/*URLGetFound The shortened URL to visit that will redirect to the given full URL.

swagger:response urlGetFound
*/
type URLGetFound struct {
	/*The full URL that the redirect leads to.

	 */
	Location string `json:"Location"`
}

// NewURLGetFound creates URLGetFound with default headers values
func NewURLGetFound() *URLGetFound {

	return &URLGetFound{}
}

// WithLocation adds the location to the url get found response
func (o *URLGetFound) WithLocation(location string) *URLGetFound {
	o.Location = location
	return o
}

// SetLocation sets the location to the url get found response
func (o *URLGetFound) SetLocation(location string) {
	o.Location = location
}

// WriteResponse to the client
func (o *URLGetFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Location

	location := o.Location
	if location != "" {
		rw.Header().Set("Location", location)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(302)
}

// URLGetNotFoundCode is the HTTP code returned for type URLGetNotFound
const URLGetNotFoundCode int = 404

/*URLGetNotFound The shortened URL expired or never existed.

swagger:response urlGetNotFound
*/
type URLGetNotFound struct {
}

// NewURLGetNotFound creates URLGetNotFound with default headers values
func NewURLGetNotFound() *URLGetNotFound {

	return &URLGetNotFound{}
}

// WriteResponse to the client
func (o *URLGetNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
