// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MicahParks/terse-URL/models"
)

// URLTrackOKCode is the HTTP code returned for type URLTrackOK
const URLTrackOKCode int = 200

/*URLTrackOK An array of visit info for the given shortened URL.

swagger:response urlTrackOK
*/
type URLTrackOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Visit `json:"body,omitempty"`
}

// NewURLTrackOK creates URLTrackOK with default headers values
func NewURLTrackOK() *URLTrackOK {

	return &URLTrackOK{}
}

// WithPayload adds the payload to the url track o k response
func (o *URLTrackOK) WithPayload(payload []*models.Visit) *URLTrackOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the url track o k response
func (o *URLTrackOK) SetPayload(payload []*models.Visit) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *URLTrackOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Visit, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*URLTrackDefault Unexpected error.

swagger:response urlTrackDefault
*/
type URLTrackDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewURLTrackDefault creates URLTrackDefault with default headers values
func NewURLTrackDefault(code int) *URLTrackDefault {
	if code <= 0 {
		code = 500
	}

	return &URLTrackDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the url track default response
func (o *URLTrackDefault) WithStatusCode(code int) *URLTrackDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the url track default response
func (o *URLTrackDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the url track default response
func (o *URLTrackDefault) WithPayload(payload *models.Error) *URLTrackDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the url track default response
func (o *URLTrackDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *URLTrackDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
