// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// NewURLDeleteParams creates a new URLDeleteParams object
// no default values defined in spec.
func NewURLDeleteParams() URLDeleteParams {

	return URLDeleteParams{}
}

// URLDeleteParams contains all the bound params for the url delete operation
// typically these are obtained from a http.Request
//
// swagger:parameters urlDelete
type URLDeleteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	Shortened string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewURLDeleteParams() beforehand.
func (o *URLDeleteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body string
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("shortened", "body", ""))
			} else {
				res = append(res, errors.NewParseError("shortened", "body", "", err))
			}
		} else {
			// no validation required on inline body
			o.Shortened = body
		}
	} else {
		res = append(res, errors.Required("shortened", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
