// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MicahParks/terse-URL/models"
)

// URLDeleteOKCode is the HTTP code returned for type URLDeleteOK
const URLDeleteOKCode int = 200

/*URLDeleteOK The shortened URL was successfully deleted from the backend storage.

swagger:response urlDeleteOK
*/
type URLDeleteOK struct {
}

// NewURLDeleteOK creates URLDeleteOK with default headers values
func NewURLDeleteOK() *URLDeleteOK {

	return &URLDeleteOK{}
}

// WriteResponse to the client
func (o *URLDeleteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*URLDeleteDefault Unexpected error.

swagger:response urlDeleteDefault
*/
type URLDeleteDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewURLDeleteDefault creates URLDeleteDefault with default headers values
func NewURLDeleteDefault(code int) *URLDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &URLDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the url delete default response
func (o *URLDeleteDefault) WithStatusCode(code int) *URLDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the url delete default response
func (o *URLDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the url delete default response
func (o *URLDeleteDefault) WithPayload(payload *models.Error) *URLDeleteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the url delete default response
func (o *URLDeleteDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *URLDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
