// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/MicahParks/terse-URL/models"
)

// URLDumpShortenedHandlerFunc turns a function with the right signature into a url dump shortened handler
type URLDumpShortenedHandlerFunc func(URLDumpShortenedParams, *models.JWTInfo) middleware.Responder

// Handle executing the request and returning a response
func (fn URLDumpShortenedHandlerFunc) Handle(params URLDumpShortenedParams, principal *models.JWTInfo) middleware.Responder {
	return fn(params, principal)
}

// URLDumpShortenedHandler interface for that can handle valid url dump shortened params
type URLDumpShortenedHandler interface {
	Handle(URLDumpShortenedParams, *models.JWTInfo) middleware.Responder
}

// NewURLDumpShortened creates a new http.Handler for the url dump shortened operation
func NewURLDumpShortened(ctx *middleware.Context, handler URLDumpShortenedHandler) *URLDumpShortened {
	return &URLDumpShortened{Context: ctx, Handler: handler}
}

/*URLDumpShortened swagger:route GET /api/dump/{shortened} urlDumpShortened

URLDumpShortened url dump shortened API

*/
type URLDumpShortened struct {
	Context *middleware.Context
	Handler URLDumpShortenedHandler
}

func (o *URLDumpShortened) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewURLDumpShortenedParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.JWTInfo
	if uprinc != nil {
		principal = uprinc.(*models.JWTInfo) // this is really a models.JWTInfo, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
