// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MicahParks/terse-URL/models"
)

// URLCustomOKCode is the HTTP code returned for type URLCustomOK
const URLCustomOKCode int = 200

/*URLCustomOK The shortened URL to visit that will redirect to the given full URL.

swagger:response urlCustomOK
*/
type URLCustomOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewURLCustomOK creates URLCustomOK with default headers values
func NewURLCustomOK() *URLCustomOK {

	return &URLCustomOK{}
}

// WithPayload adds the payload to the url custom o k response
func (o *URLCustomOK) WithPayload(payload string) *URLCustomOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the url custom o k response
func (o *URLCustomOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *URLCustomOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*URLCustomDefault Unexpected error.

swagger:response urlCustomDefault
*/
type URLCustomDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewURLCustomDefault creates URLCustomDefault with default headers values
func NewURLCustomDefault(code int) *URLCustomDefault {
	if code <= 0 {
		code = 500
	}

	return &URLCustomDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the url custom default response
func (o *URLCustomDefault) WithStatusCode(code int) *URLCustomDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the url custom default response
func (o *URLCustomDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the url custom default response
func (o *URLCustomDefault) WithPayload(payload *models.Error) *URLCustomDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the url custom default response
func (o *URLCustomDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *URLCustomDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
