// Code generated by go-swagger; DO NOT EDIT.

// Package restapi shakesearch
//
//  A ProlificLabs take-home challenge. https://github.com/ProlificLabs/shakesearch.
//  Schemes:
//    http
//  Host: shakesearch.micahparks.com
//  BasePath: /
//  Version: 0.0.1
//  License: MIT https://opensource.org/licenses/MIT
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
