// Code generated by go-swagger; DO NOT EDIT.

// Package restapi terseurl
//
//  The Terse URL shortener.
//  Schemes:
//    http
//    https
//  Host: terseurl.com
//  BasePath: /
//  Version: 0.0.3
//  License: AGPL-3.0 https://opensource.org/licenses/MIT
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - text/html
//    - application/json
//
// swagger:meta
package restapi
