// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Terse URL
//
//  The Terse URL shortener.
//  Schemes:
//    http
//  Host: localhost:30000
//  BasePath: /
//  Version: 0.0.1
//  License: MIT https://opensource.org/licenses/MIT
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
