// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "Terse URL",
    "version": "0.0.1"
  },
  "host": "shorten.micahparks.com",
  "basePath": "/",
  "paths": {
    "/api/alive": {
      "get": {
        "description": "For Caddy to determine if the upstream provider (this executable) is alive.",
        "operationId": "alive",
        "responses": {
          "200": {
            "description": "Service is alive."
          }
        }
      }
    },
    "/api/custom": {
      "post": {
        "security": [
          {
            "JWT": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Give a full URL and a custom shortened URL, create the redirection to it. Custom URLs cannot be \"api\".",
        "operationId": "urlCustom",
        "parameters": [
          {
            "name": "tersePair",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "original",
                "shortened"
              ],
              "properties": {
                "deleteAt": {
                  "type": "string",
                  "format": "date-time"
                },
                "originalURL": {
                  "type": "string"
                },
                "shortenedURL": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The shortened URL to visit that will redirect to the given full URL.",
            "schema": {
              "type": "string"
            }
          },
          "default": {
            "description": "Unexpected error.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/api/delete": {
      "delete": {
        "security": [
          {
            "JWT": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Delete the given shortened URL from the backend storage, cause the shortened URL to immediately expire.",
        "operationId": "urlDelete",
        "parameters": [
          {
            "name": "shortened",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The shortened URL was successfully deleted from the backend storage."
          },
          "default": {
            "description": "Unexpected error.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/api/random": {
      "post": {
        "security": [
          {
            "JWT": []
          }
        ],
        "description": "Give a full URL and get a shortened URL that will redirect to it.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "operationId": "urlRandom",
        "parameters": [
          {
            "name": "original",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "original"
              ],
              "properties": {
                "URL": {
                  "type": "string"
                },
                "deleteAt": {
                  "type": "string",
                  "format": "date-time"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The shortened URL to visit that will redirect to the given full URL.",
            "schema": {
              "type": "string"
            }
          },
          "default": {
            "description": "Unexpected error.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/api/track/{shortened}": {
      "get": {
        "security": [
          {
            "JWT": []
          }
        ],
        "description": "Get the tracking info for the shortened URL.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "operationId": "urlTrack",
        "parameters": [
          {
            "type": "string",
            "name": "shortened",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "An array of visit info for the given shortened URL.",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Visit"
              }
            }
          },
          "default": {
            "description": "Unexpected error.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/frontend/{path}": {
      "get": {
        "description": "Get a frontend asset to interact with the application via a web browser.",
        "operationId": "frontend",
        "parameters": [
          {
            "type": "string",
            "name": "path",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The case insensitive substring to search for a shortened URL. (Only applied when applicable.)",
            "name": "shortened",
            "in": "query"
          },
          {
            "type": "string",
            "description": "The case insensitive substring to search for a original URL. (Only applied when applicable.)",
            "name": "original",
            "in": "query"
          },
          {
            "type": "boolean",
            "default": true,
            "description": "If true, sort the \"sortThis\" query enum in descending lexicographical order.",
            "name": "sortDescending",
            "in": "query"
          },
          {
            "enum": [
              "original",
              "shortened",
              "visits"
            ],
            "type": "string",
            "default": "visits",
            "description": "The enum to sort the table results by. (Only applied when applicable.)",
            "name": "sortThis",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "The frontend asset.",
            "schema": {
              "type": "file"
            }
          },
          "404": {
            "description": "The requested asset was not found.",
            "schema": {
              "type": "string"
            }
          },
          "default": {
            "description": "Unexpected error.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/{shortened}": {
      "get": {
        "description": "Use the shortened URL. It will redirect to the full URL if it has not expired.",
        "operationId": "urlGet",
        "parameters": [
          {
            "type": "string",
            "name": "shortened",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "302": {
            "description": "The shortened URL to visit that will redirect to the given full URL.",
            "headers": {
              "Location": {
                "type": "string",
                "description": "The full URL that the redirect leads to."
              }
            }
          },
          "404": {
            "description": "The shortened URL expired or never existed."
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "JWTInfo": {
      "properties": {
        "email": {
          "type": "string"
        },
        "groups": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "Visit": {
      "required": [
        "accessed",
        "ip"
      ],
      "properties": {
        "accessed": {
          "type": "string",
          "format": "date-time"
        },
        "ip": {
          "type": "string"
        },
        "userAgent": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "JWT": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "Terse URL",
    "version": "0.0.1"
  },
  "host": "shorten.micahparks.com",
  "basePath": "/",
  "paths": {
    "/api/alive": {
      "get": {
        "description": "For Caddy to determine if the upstream provider (this executable) is alive.",
        "operationId": "alive",
        "responses": {
          "200": {
            "description": "Service is alive."
          }
        }
      }
    },
    "/api/custom": {
      "post": {
        "security": [
          {
            "JWT": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Give a full URL and a custom shortened URL, create the redirection to it. Custom URLs cannot be \"api\".",
        "operationId": "urlCustom",
        "parameters": [
          {
            "name": "tersePair",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "original",
                "shortened"
              ],
              "properties": {
                "deleteAt": {
                  "type": "string",
                  "format": "date-time"
                },
                "originalURL": {
                  "type": "string"
                },
                "shortenedURL": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The shortened URL to visit that will redirect to the given full URL.",
            "schema": {
              "type": "string"
            }
          },
          "default": {
            "description": "Unexpected error.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/api/delete": {
      "delete": {
        "security": [
          {
            "JWT": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Delete the given shortened URL from the backend storage, cause the shortened URL to immediately expire.",
        "operationId": "urlDelete",
        "parameters": [
          {
            "name": "shortened",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The shortened URL was successfully deleted from the backend storage."
          },
          "default": {
            "description": "Unexpected error.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/api/random": {
      "post": {
        "security": [
          {
            "JWT": []
          }
        ],
        "description": "Give a full URL and get a shortened URL that will redirect to it.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "operationId": "urlRandom",
        "parameters": [
          {
            "name": "original",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "original"
              ],
              "properties": {
                "URL": {
                  "type": "string"
                },
                "deleteAt": {
                  "type": "string",
                  "format": "date-time"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The shortened URL to visit that will redirect to the given full URL.",
            "schema": {
              "type": "string"
            }
          },
          "default": {
            "description": "Unexpected error.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/api/track/{shortened}": {
      "get": {
        "security": [
          {
            "JWT": []
          }
        ],
        "description": "Get the tracking info for the shortened URL.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "operationId": "urlTrack",
        "parameters": [
          {
            "type": "string",
            "name": "shortened",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "An array of visit info for the given shortened URL.",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Visit"
              }
            }
          },
          "default": {
            "description": "Unexpected error.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/frontend/{path}": {
      "get": {
        "description": "Get a frontend asset to interact with the application via a web browser.",
        "operationId": "frontend",
        "parameters": [
          {
            "type": "string",
            "name": "path",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The case insensitive substring to search for a shortened URL. (Only applied when applicable.)",
            "name": "shortened",
            "in": "query"
          },
          {
            "type": "string",
            "description": "The case insensitive substring to search for a original URL. (Only applied when applicable.)",
            "name": "original",
            "in": "query"
          },
          {
            "type": "boolean",
            "default": true,
            "description": "If true, sort the \"sortThis\" query enum in descending lexicographical order.",
            "name": "sortDescending",
            "in": "query"
          },
          {
            "enum": [
              "original",
              "shortened",
              "visits"
            ],
            "type": "string",
            "default": "visits",
            "description": "The enum to sort the table results by. (Only applied when applicable.)",
            "name": "sortThis",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "The frontend asset.",
            "schema": {
              "type": "file"
            }
          },
          "404": {
            "description": "The requested asset was not found.",
            "schema": {
              "type": "string"
            }
          },
          "default": {
            "description": "Unexpected error.",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/{shortened}": {
      "get": {
        "description": "Use the shortened URL. It will redirect to the full URL if it has not expired.",
        "operationId": "urlGet",
        "parameters": [
          {
            "type": "string",
            "name": "shortened",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "302": {
            "description": "The shortened URL to visit that will redirect to the given full URL.",
            "headers": {
              "Location": {
                "type": "string",
                "description": "The full URL that the redirect leads to."
              }
            }
          },
          "404": {
            "description": "The shortened URL expired or never existed."
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "JWTInfo": {
      "properties": {
        "email": {
          "type": "string"
        },
        "groups": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "Visit": {
      "required": [
        "accessed",
        "ip"
      ],
      "properties": {
        "accessed": {
          "type": "string",
          "format": "date-time"
        },
        "ip": {
          "type": "string"
        },
        "userAgent": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "JWT": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
}
