// Code generated by go-swagger; DO NOT EDIT.

package frontend

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"
)

// FrontendStaticOKCode is the HTTP code returned for type FrontendStaticOK
const FrontendStaticOKCode int = 200

/*FrontendStaticOK The frontend asset.

swagger:response frontendStaticOK
*/
type FrontendStaticOK struct {

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewFrontendStaticOK creates FrontendStaticOK with default headers values
func NewFrontendStaticOK() *FrontendStaticOK {

	return &FrontendStaticOK{}
}

// WithPayload adds the payload to the frontend static o k response
func (o *FrontendStaticOK) WithPayload(payload io.ReadCloser) *FrontendStaticOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the frontend static o k response
func (o *FrontendStaticOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FrontendStaticOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// FrontendStaticNotFoundCode is the HTTP code returned for type FrontendStaticNotFound
const FrontendStaticNotFoundCode int = 404

/*FrontendStaticNotFound The file was not found.

swagger:response frontendStaticNotFound
*/
type FrontendStaticNotFound struct {
}

// NewFrontendStaticNotFound creates FrontendStaticNotFound with default headers values
func NewFrontendStaticNotFound() *FrontendStaticNotFound {

	return &FrontendStaticNotFound{}
}

// WriteResponse to the client
func (o *FrontendStaticNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
