// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewPublicRedirectParams creates a new PublicRedirectParams object
//
// There are no default values defined in the spec.
func NewPublicRedirectParams() PublicRedirectParams {

	return PublicRedirectParams{}
}

// PublicRedirectParams contains all the bound params for the public redirect operation
// typically these are obtained from a http.Request
//
// swagger:parameters publicRedirect
type PublicRedirectParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	ShortenedURL string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPublicRedirectParams() beforehand.
func (o *PublicRedirectParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rShortenedURL, rhkShortenedURL, _ := route.Params.GetOK("shortenedURL")
	if err := o.bindShortenedURL(rShortenedURL, rhkShortenedURL, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindShortenedURL binds and validates parameter ShortenedURL from path.
func (o *PublicRedirectParams) bindShortenedURL(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.ShortenedURL = raw

	return nil
}
