// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"
)

// PublicRedirectOKCode is the HTTP code returned for type PublicRedirectOK
const PublicRedirectOKCode int = 200

/*PublicRedirectOK The HTML document containing a social media link preview and or JavaScript fingerprinting. Any visitor will be automatically redirected to the original link with JavaScript.

swagger:response publicRedirectOK
*/
type PublicRedirectOK struct {

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewPublicRedirectOK creates PublicRedirectOK with default headers values
func NewPublicRedirectOK() *PublicRedirectOK {

	return &PublicRedirectOK{}
}

// WithPayload adds the payload to the public redirect o k response
func (o *PublicRedirectOK) WithPayload(payload io.ReadCloser) *PublicRedirectOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the public redirect o k response
func (o *PublicRedirectOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PublicRedirectOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PublicRedirectMovedPermanentlyCode is the HTTP code returned for type PublicRedirectMovedPermanently
const PublicRedirectMovedPermanentlyCode int = 301

/*PublicRedirectMovedPermanently An HTTP response that will server as a permanent redirect to the shortened URL's full URL.

swagger:response publicRedirectMovedPermanently
*/
type PublicRedirectMovedPermanently struct {
	/*The full URL that the redirect leads to.

	 */
	Location string `json:"Location"`
}

// NewPublicRedirectMovedPermanently creates PublicRedirectMovedPermanently with default headers values
func NewPublicRedirectMovedPermanently() *PublicRedirectMovedPermanently {

	return &PublicRedirectMovedPermanently{}
}

// WithLocation adds the location to the public redirect moved permanently response
func (o *PublicRedirectMovedPermanently) WithLocation(location string) *PublicRedirectMovedPermanently {
	o.Location = location
	return o
}

// SetLocation sets the location to the public redirect moved permanently response
func (o *PublicRedirectMovedPermanently) SetLocation(location string) {
	o.Location = location
}

// WriteResponse to the client
func (o *PublicRedirectMovedPermanently) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Location

	location := o.Location
	if location != "" {
		rw.Header().Set("Location", location)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(301)
}

// PublicRedirectFoundCode is the HTTP code returned for type PublicRedirectFound
const PublicRedirectFoundCode int = 302

/*PublicRedirectFound An HTTP response that will serve as a temporary redirect to the shortened URL's full URL.

swagger:response publicRedirectFound
*/
type PublicRedirectFound struct {
	/*The full URL that the redirect leads to.

	 */
	Location string `json:"Location"`
}

// NewPublicRedirectFound creates PublicRedirectFound with default headers values
func NewPublicRedirectFound() *PublicRedirectFound {

	return &PublicRedirectFound{}
}

// WithLocation adds the location to the public redirect found response
func (o *PublicRedirectFound) WithLocation(location string) *PublicRedirectFound {
	o.Location = location
	return o
}

// SetLocation sets the location to the public redirect found response
func (o *PublicRedirectFound) SetLocation(location string) {
	o.Location = location
}

// WriteResponse to the client
func (o *PublicRedirectFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Location

	location := o.Location
	if location != "" {
		rw.Header().Set("Location", location)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(302)
}

// PublicRedirectNotFoundCode is the HTTP code returned for type PublicRedirectNotFound
const PublicRedirectNotFoundCode int = 404

/*PublicRedirectNotFound The shortened URL expired or never existed.

swagger:response publicRedirectNotFound
*/
type PublicRedirectNotFound struct {
}

// NewPublicRedirectNotFound creates PublicRedirectNotFound with default headers values
func NewPublicRedirectNotFound() *PublicRedirectNotFound {

	return &PublicRedirectNotFound{}
}

// WriteResponse to the client
func (o *PublicRedirectNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
