// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// TersePrefixOKCode is the HTTP code returned for type TersePrefixOK
const TersePrefixOKCode int = 200

/*TersePrefixOK The HTTP prefix all shortened URLs have.

swagger:response tersePrefixOK
*/
type TersePrefixOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewTersePrefixOK creates TersePrefixOK with default headers values
func NewTersePrefixOK() *TersePrefixOK {

	return &TersePrefixOK{}
}

// WithPayload adds the payload to the terse prefix o k response
func (o *TersePrefixOK) WithPayload(payload string) *TersePrefixOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the terse prefix o k response
func (o *TersePrefixOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TersePrefixOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
