// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"
)

// TerseRedirectOKCode is the HTTP code returned for type TerseRedirectOK
const TerseRedirectOKCode int = 200

/*TerseRedirectOK The HTML document containing a social media link preview and or JavaScript fingerprinting. Any visitor will be automatically redirected to the original link with JavaScript.

swagger:response terseRedirectOK
*/
type TerseRedirectOK struct {

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewTerseRedirectOK creates TerseRedirectOK with default headers values
func NewTerseRedirectOK() *TerseRedirectOK {

	return &TerseRedirectOK{}
}

// WithPayload adds the payload to the terse redirect o k response
func (o *TerseRedirectOK) WithPayload(payload io.ReadCloser) *TerseRedirectOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the terse redirect o k response
func (o *TerseRedirectOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *TerseRedirectOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// TerseRedirectMovedPermanentlyCode is the HTTP code returned for type TerseRedirectMovedPermanently
const TerseRedirectMovedPermanentlyCode int = 301

/*TerseRedirectMovedPermanently An HTTP response that will server as a permanent redirect to the shortened URL's full URL.

swagger:response terseRedirectMovedPermanently
*/
type TerseRedirectMovedPermanently struct {
	/*The full URL that the redirect leads to.

	 */
	Location string `json:"Location"`
}

// NewTerseRedirectMovedPermanently creates TerseRedirectMovedPermanently with default headers values
func NewTerseRedirectMovedPermanently() *TerseRedirectMovedPermanently {

	return &TerseRedirectMovedPermanently{}
}

// WithLocation adds the location to the terse redirect moved permanently response
func (o *TerseRedirectMovedPermanently) WithLocation(location string) *TerseRedirectMovedPermanently {
	o.Location = location
	return o
}

// SetLocation sets the location to the terse redirect moved permanently response
func (o *TerseRedirectMovedPermanently) SetLocation(location string) {
	o.Location = location
}

// WriteResponse to the client
func (o *TerseRedirectMovedPermanently) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Location

	location := o.Location
	if location != "" {
		rw.Header().Set("Location", location)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(301)
}

// TerseRedirectFoundCode is the HTTP code returned for type TerseRedirectFound
const TerseRedirectFoundCode int = 302

/*TerseRedirectFound An HTTP response that will serve as a temporary redirect to the shortened URL's full URL.

swagger:response terseRedirectFound
*/
type TerseRedirectFound struct {
	/*The full URL that the redirect leads to.

	 */
	Location string `json:"Location"`
}

// NewTerseRedirectFound creates TerseRedirectFound with default headers values
func NewTerseRedirectFound() *TerseRedirectFound {

	return &TerseRedirectFound{}
}

// WithLocation adds the location to the terse redirect found response
func (o *TerseRedirectFound) WithLocation(location string) *TerseRedirectFound {
	o.Location = location
	return o
}

// SetLocation sets the location to the terse redirect found response
func (o *TerseRedirectFound) SetLocation(location string) {
	o.Location = location
}

// WriteResponse to the client
func (o *TerseRedirectFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Location

	location := o.Location
	if location != "" {
		rw.Header().Set("Location", location)
	}

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(302)
}

// TerseRedirectNotFoundCode is the HTTP code returned for type TerseRedirectNotFound
const TerseRedirectNotFoundCode int = 404

/*TerseRedirectNotFound The shortened URL expired or never existed.

swagger:response terseRedirectNotFound
*/
type TerseRedirectNotFound struct {
}

// NewTerseRedirectNotFound creates TerseRedirectNotFound with default headers values
func NewTerseRedirectNotFound() *TerseRedirectNotFound {

	return &TerseRedirectNotFound{}
}

// WriteResponse to the client
func (o *TerseRedirectNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
