// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// SystemAliveOKCode is the HTTP code returned for type SystemAliveOK
const SystemAliveOKCode int = 200

/*SystemAliveOK Service is alive.

swagger:response systemAliveOK
*/
type SystemAliveOK struct {
}

// NewSystemAliveOK creates SystemAliveOK with default headers values
func NewSystemAliveOK() *SystemAliveOK {

	return &SystemAliveOK{}
}

// WriteResponse to the client
func (o *SystemAliveOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
