// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Dump dump
//
// swagger:model Dump
type Dump struct {

	// terse
	Terse *Terse `json:"terse,omitempty"`

	// visits
	Visits []*Visit `json:"visits"`
}

// Validate validates this dump
func (m *Dump) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTerse(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVisits(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Dump) validateTerse(formats strfmt.Registry) error {

	if swag.IsZero(m.Terse) { // not required
		return nil
	}

	if m.Terse != nil {
		if err := m.Terse.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("terse")
			}
			return err
		}
	}

	return nil
}

func (m *Dump) validateVisits(formats strfmt.Registry) error {

	if swag.IsZero(m.Visits) { // not required
		return nil
	}

	for i := 0; i < len(m.Visits); i++ {
		if swag.IsZero(m.Visits[i]) { // not required
			continue
		}

		if m.Visits[i] != nil {
			if err := m.Visits[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("visits" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Dump) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Dump) UnmarshalBinary(b []byte) error {
	var res Dump
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
