// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Export export
//
// swagger:model Export
type Export struct {

	// terse
	Terse *Terse `json:"terse,omitempty"`

	// visits
	Visits []Visit `json:"visits"`
}

// Validate validates this export
func (m *Export) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTerse(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVisits(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Export) validateTerse(formats strfmt.Registry) error {
	if swag.IsZero(m.Terse) { // not required
		return nil
	}

	if m.Terse != nil {
		if err := m.Terse.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("terse")
			}
			return err
		}
	}

	return nil
}

func (m *Export) validateVisits(formats strfmt.Registry) error {
	if swag.IsZero(m.Visits) { // not required
		return nil
	}

	for i := 0; i < len(m.Visits); i++ {

		if err := m.Visits[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("visits" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

// ContextValidate validate this export based on the context it is used
func (m *Export) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTerse(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVisits(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Export) contextValidateTerse(ctx context.Context, formats strfmt.Registry) error {

	if m.Terse != nil {
		if err := m.Terse.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("terse")
			}
			return err
		}
	}

	return nil
}

func (m *Export) contextValidateVisits(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Visits); i++ {

		if err := m.Visits[i].ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("visits" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Export) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Export) UnmarshalBinary(b []byte) error {
	var res Export
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
