// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// JWTInfo j w t info
//
// swagger:model JWTInfo
type JWTInfo struct {

	// email
	Email string `json:"email,omitempty"`

	// groups
	Groups []string `json:"groups"`
}

// Validate validates this j w t info
func (m *JWTInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *JWTInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JWTInfo) UnmarshalBinary(b []byte) error {
	var res JWTInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
