// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MediaPreview media preview
//
// swagger:model MediaPreview
type MediaPreview struct {

	// audio URL
	AudioURL string `json:"audioURL,omitempty"`

	// canonical URL
	// Required: true
	CanonicalURL *string `json:"canonicalURL"`

	// description
	Description string `json:"description,omitempty"`

	// determiner
	Determiner string `json:"determiner,omitempty"`

	// image URL
	// Required: true
	ImageURL *string `json:"imageURL"`

	// locale
	Locale string `json:"locale,omitempty"`

	// locale alt
	LocaleAlt string `json:"localeAlt,omitempty"`

	// site name
	SiteName string `json:"siteName,omitempty"`

	// title
	// Required: true
	Title *string `json:"title"`

	// twitter
	Twitter *Twitter `json:"twitter,omitempty"`

	// type
	// Required: true
	Type *string `json:"type"`

	// video URL
	VideoURL string `json:"videoURL,omitempty"`
}

// Validate validates this media preview
func (m *MediaPreview) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCanonicalURL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateImageURL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTitle(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTwitter(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MediaPreview) validateCanonicalURL(formats strfmt.Registry) error {

	if err := validate.Required("canonicalURL", "body", m.CanonicalURL); err != nil {
		return err
	}

	return nil
}

func (m *MediaPreview) validateImageURL(formats strfmt.Registry) error {

	if err := validate.Required("imageURL", "body", m.ImageURL); err != nil {
		return err
	}

	return nil
}

func (m *MediaPreview) validateTitle(formats strfmt.Registry) error {

	if err := validate.Required("title", "body", m.Title); err != nil {
		return err
	}

	return nil
}

func (m *MediaPreview) validateTwitter(formats strfmt.Registry) error {

	if swag.IsZero(m.Twitter) { // not required
		return nil
	}

	if m.Twitter != nil {
		if err := m.Twitter.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("twitter")
			}
			return err
		}
	}

	return nil
}

func (m *MediaPreview) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MediaPreview) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MediaPreview) UnmarshalBinary(b []byte) error {
	var res MediaPreview
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
