// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// OpenGraph open graph
//
// swagger:model OpenGraph
type OpenGraph map[string]string

// Validate validates this open graph
func (m OpenGraph) Validate(formats strfmt.Registry) error {
	return nil
}
