// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VisitsSummary visits summary
//
// swagger:model VisitsSummary
type VisitsSummary struct {

	// visit count
	VisitCount uint64 `json:"visitCount,omitempty"`
}

// Validate validates this visits summary
func (m *VisitsSummary) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this visits summary based on context it is used
func (m *VisitsSummary) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VisitsSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VisitsSummary) UnmarshalBinary(b []byte) error {
	var res VisitsSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
